[build]
  # Build command for FastHTML application
  command = "python3 build_static.py"
  
  # Publish directory for static files
  publish = "dist"

[build.environment]
  # Python version
  PYTHON_VERSION = "3.11"

# Redirect rules for clean URLs
[[redirects]]
  from = "/seals-and-stamps"
  to = "/seals-and-stamps.html"
  status = 200

[[redirects]]
  from = "/self-inking-stamps"
  to = "/self-inking-stamps.html"
  status = 200

[[redirects]]
  from = "/engraving"
  to = "/engraving.html"
  status = 200

[[redirects]]
  from = "/stationery"
  to = "/stationery.html"
  status = 200

[[redirects]]
  from = "/products-and-services"
  to = "/products-and-services.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

# Fallback to index for SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Cache control for HTML
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
